### ISSUE TITLE
https://d.yttr.org/ is down

### ISSUE THREAD

**Issue by memtest2** [yttrian/drect#1]
:p

**Comment by memtest2** [comment]
![image](https://user-images.githubusercontent.com/76135394/108869408-154e0400-75ef-11eb-9e54-1c0775289a28.png)

**Comment by yttrian** [comment]
Hmm. Looks like GitHub didn't properly update its certificate, since the page is hosted on GitHub Pages. I'm going to try giving it a day, and check back on it to see if it resolved itself. Otherwise, I may need to look for a better solution.

**Comment by memtest2** [comment]
> Hmm. Looks like GitHub didn't properly update its certificate, since the page is hosted on GitHub Pages. I'm going to try giving it a day, and check back on it to see if it resolved itself. Otherwise, I may need to look for a better solution.

its been like this for at least 2 days now

**Comment by yttrian** [comment]
Looks to be working now.
